import { Category, Menu, Profile, Transaction } from '../types/database';

export const INITIAL_PROFILES: Profile[] = [
  {
    id: '00000000-0000-0000-0000-000000000001',
    full_name: 'Bu Hj. Ratna (Pemilik)',
    role: 'admin',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: '00000000-0000-0000-0000-000000000002',
    full_name: 'Budi Santoso (Kasir Shift Pagi)',
    role: 'kasir',
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Makanan/Lauk Utama' },
  { id: 'cat-2', name: 'Sayuran' },
  { id: 'cat-3', name: 'Gorengan/Pelengkap' },
  { id: 'cat-4', name: 'Minuman' },
  { id: 'cat-5', name: 'Paket Hemat' },
];

export const INITIAL_MENUS: Menu[] = [
  // Lauk Utama
  {
    id: 'm-01',
    sku_code: 'LK-01',
    name: 'Ayam Goreng Lengkuas',
    category_id: 'cat-1',
    price: 15000,
    daily_stock: 35,
    is_available: true,
    image_url: '🍗',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'm-02',
    sku_code: 'LK-02',
    name: 'Rendang Sapi Basah',
    category_id: 'cat-1',
    price: 18000,
    daily_stock: 25,
    is_available: true,
    image_url: '🥩',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'm-03',
    sku_code: 'LK-03',
    name: 'Telur Balado Balut Cabai',
    category_id: 'cat-1',
    price: 7000,
    daily_stock: 40,
    is_available: true,
    image_url: '🍳',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'm-04',
    sku_code: 'LK-04',
    name: 'Ikan Kembung Goreng Kering',
    category_id: 'cat-1',
    price: 14000,
    daily_stock: 18,
    is_available: true,
    image_url: '🐟',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'm-05',
    sku_code: 'LK-05',
    name: 'Tongkol Suwir Pedas',
    category_id: 'cat-1',
    price: 12000,
    daily_stock: 22,
    is_available: true,
    image_url: '🍛',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'm-06',
    sku_code: 'LK-06',
    name: 'Ayam Bakar Madu Pedas Manis',
    category_id: 'cat-1',
    price: 16000,
    daily_stock: 30,
    is_available: true,
    image_url: '🍖',
    updated_at: new Date().toISOString(),
  },

  // Sayuran
  {
    id: 'm-07',
    sku_code: 'SY-01',
    name: 'Sayur Asem Khas Betawi',
    category_id: 'cat-2',
    price: 6000,
    daily_stock: 45,
    is_available: true,
    image_url: '🥣',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'm-08',
    sku_code: 'SY-02',
    name: 'Sayur Lodeh Nangka & Labu',
    category_id: 'cat-2',
    price: 7000,
    daily_stock: 35,
    is_available: true,
    image_url: '🍲',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'm-09',
    sku_code: 'SY-03',
    name: 'Tumis Kangkung Belacan',
    category_id: 'cat-2',
    price: 6000,
    daily_stock: 30,
    is_available: true,
    image_url: '🥬',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'm-10',
    sku_code: 'SY-04',
    name: 'Capcay Kuah Kental Jawa',
    category_id: 'cat-2',
    price: 8000,
    daily_stock: 25,
    is_available: true,
    image_url: '🥕',
    updated_at: new Date().toISOString(),
  },

  // Gorengan / Pelengkap
  {
    id: 'm-11',
    sku_code: 'GP-01',
    name: 'Nasi Putih Pulen Wangi',
    category_id: 'cat-3',
    price: 5000,
    daily_stock: 120,
    is_available: true,
    image_url: '🍚',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'm-12',
    sku_code: 'GP-02',
    name: 'Tempe Mendoan Gurih (2 pcs)',
    category_id: 'cat-3',
    price: 4000,
    daily_stock: 60,
    is_available: true,
    image_url: '🧇',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'm-13',
    sku_code: 'GP-03',
    name: 'Bakwan Jagung Manis Renyah',
    category_id: 'cat-3',
    price: 3000,
    daily_stock: 50,
    is_available: true,
    image_url: '🌽',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'm-14',
    sku_code: 'GP-04',
    name: 'Tahu Isi Sayur Crispy',
    category_id: 'cat-3',
    price: 3000,
    daily_stock: 40,
    is_available: true,
    image_url: '🥟',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'm-15',
    sku_code: 'GP-05',
    name: 'Sambal Terasi Ulek Dadak',
    category_id: 'cat-3',
    price: 2500,
    daily_stock: 80,
    is_available: true,
    image_url: '🌶️',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'm-16',
    sku_code: 'GP-06',
    name: 'Kerupuk Putih Blek Kaleng',
    category_id: 'cat-3',
    price: 2000,
    daily_stock: 90,
    is_available: true,
    image_url: '🍥',
    updated_at: new Date().toISOString(),
  },

  // Minuman
  {
    id: 'm-17',
    sku_code: 'MN-01',
    name: 'Es Teh Manis Jumbo Solo',
    category_id: 'cat-4',
    price: 5000,
    daily_stock: 120,
    is_available: true,
    image_url: '🥤',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'm-18',
    sku_code: 'MN-02',
    name: 'Es Jeruk Peras Murni',
    category_id: 'cat-4',
    price: 7000,
    daily_stock: 50,
    is_available: true,
    image_url: '🍊',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'm-19',
    sku_code: 'MN-03',
    name: 'Kopi Tubruk Robusta Panas',
    category_id: 'cat-4',
    price: 5000,
    daily_stock: 40,
    is_available: true,
    image_url: '☕',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'm-20',
    sku_code: 'MN-04',
    name: 'Air Mineral Botol 600ml',
    category_id: 'cat-4',
    price: 4000,
    daily_stock: 75,
    is_available: true,
    image_url: '💧',
    updated_at: new Date().toISOString(),
  },

  // Paket Hemat
  {
    id: 'm-21',
    sku_code: 'PK-01',
    name: 'Paket Rames Ayam Lengkuas Komplit',
    category_id: 'cat-5',
    price: 24000,
    daily_stock: 30,
    is_available: true,
    image_url: '🍱',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'm-22',
    sku_code: 'PK-02',
    name: 'Paket Rames Rendang Sapi Spesial',
    category_id: 'cat-5',
    price: 28000,
    daily_stock: 25,
    is_available: true,
    image_url: '🍛',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'm-23',
    sku_code: 'PK-03',
    name: 'Paket Hemat Balado + Sayur Asem',
    category_id: 'cat-5',
    price: 18000,
    daily_stock: 35,
    is_available: true,
    image_url: '🍱',
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-001',
    invoice_number: 'INV-20260922-001',
    user_id: '00000000-0000-0000-0000-000000000002',
    cashier_name: 'Budi Santoso',
    order_type: 'dine_in',
    total_amount: 32000,
    discount: 0,
    payment_method: 'cash',
    cash_tendered: 50000,
    change_amount: 18000,
    created_at: new Date(Date.now() - 3 * 3600000).toISOString(),
    items: [
      {
        id: 'ti-01',
        transaction_id: 'tx-001',
        menu_id: 'm-01',
        menu_name: 'Ayam Goreng Lengkuas',
        quantity: 1,
        price_at_sale: 15000,
        subtotal: 15000,
        notes: 'Minta paha atas',
      },
      {
        id: 'ti-02',
        transaction_id: 'tx-001',
        menu_id: 'm-11',
        menu_name: 'Nasi Putih Pulen Wangi',
        quantity: 1,
        price_at_sale: 5000,
        subtotal: 5000,
        notes: '',
      },
      {
        id: 'ti-03',
        transaction_id: 'tx-001',
        menu_id: 'm-07',
        menu_name: 'Sayur Asem Khas Betawi',
        quantity: 1,
        price_at_sale: 6000,
        subtotal: 6000,
        notes: 'Kuah banyak',
      },
      {
        id: 'ti-04',
        transaction_id: 'tx-001',
        menu_id: 'm-17',
        menu_name: 'Es Teh Manis Jumbo Solo',
        quantity: 1,
        price_at_sale: 5000,
        subtotal: 5000,
        notes: 'Es sedikit',
      },
      {
        id: 'ti-05',
        transaction_id: 'tx-001',
        menu_id: 'm-16',
        menu_name: 'Kerupuk Putih Blek Kaleng',
        quantity: 1,
        price_at_sale: 2000,
        subtotal: 2000,
        notes: '',
      },
    ],
  },
  {
    id: 'tx-002',
    invoice_number: 'INV-20260922-002',
    user_id: '00000000-0000-0000-0000-000000000002',
    cashier_name: 'Budi Santoso',
    order_type: 'takeaway',
    total_amount: 56000,
    discount: 0,
    payment_method: 'qris',
    created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
    items: [
      {
        id: 'ti-06',
        transaction_id: 'tx-002',
        menu_id: 'm-22',
        menu_name: 'Paket Rames Rendang Sapi Spesial',
        quantity: 2,
        price_at_sale: 28000,
        subtotal: 56000,
        notes: 'Bungkus daun pisang, sambal pisah',
      },
    ],
  },
  {
    id: 'tx-003',
    invoice_number: 'INV-20260922-003',
    user_id: '00000000-0000-0000-0000-000000000002',
    cashier_name: 'Budi Santoso',
    order_type: 'dine_in',
    total_amount: 25000,
    discount: 0,
    payment_method: 'transfer',
    created_at: new Date(Date.now() - 45 * 60000).toISOString(),
    items: [
      {
        id: 'ti-07',
        transaction_id: 'tx-003',
        menu_id: 'm-23',
        menu_name: 'Paket Hemat Balado + Sayur Asem',
        quantity: 1,
        price_at_sale: 18000,
        subtotal: 18000,
        notes: '',
      },
      {
        id: 'ti-08',
        transaction_id: 'tx-003',
        menu_id: 'm-18',
        menu_name: 'Es Jeruk Peras Murni',
        quantity: 1,
        price_at_sale: 7000,
        subtotal: 7000,
        notes: 'Gula normal',
      },
    ],
  },
];
